"""add departments and student relationship

Revision ID: 4536c607cba3
Revises: 9fb4fc398ac4
Create Date: 2026-09-18 11:12:56.739628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4536c607cba3'
down_revision: Union[str, Sequence[str], None] = '9fb4fc398ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(
    "INSERT INTO departments (id, name) VALUES (1, 'Computer Science')"
    )
    op.add_column('students', sa.Column('department_id', sa.Integer(), nullable=True))
    
    op.execute(
        "UPDATE students SET department_id = 1"
        )
    
    op.alter_column(
    'students',
    'department_id',
    nullable=False
    )
    

    
    op.create_foreign_key(
        'fk_students_department_id',
        'students',
        'departments',
        ['department_id'],
        ['id']
    )
    
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_students_department_id', 'students', type_='foreignkey')
    op.drop_column('students', 'department_id')
    op.drop_table('departments')
    # ### end Alembic commands ###
